// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
    appId: '1:975047231758:web:aa889c3b400997e4dc6f5f',
    messagingSenderId: '975047231758',
    projectId: 'paydas-a4506',
    authDomain: 'paydas-a4506.firebaseapp.com',
    storageBucket: 'paydas-a4506.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: '1:975047231758:android:14f22a438891dd75dc6f5f',
    messagingSenderId: '975047231758',
    projectId: 'paydas-a4506',
    storageBucket: 'paydas-a4506.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
    appId: '1:975047231758:ios:68b6c29b9cb4fd81dc6f5f',
    messagingSenderId: '975047231758',
    projectId: 'paydas-a4506',
    storageBucket: 'paydas-a4506.firebasestorage.app',
    iosBundleId: 'com.paydas.paydasApp',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_MACOS_API_KEY'] ?? '',
    appId: '1:975047231758:ios:68b6c29b9cb4fd81dc6f5f',
    messagingSenderId: '975047231758',
    projectId: 'paydas-a4506',
    storageBucket: 'paydas-a4506.firebasestorage.app',
    iosBundleId: 'com.paydas.paydasApp',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY'] ?? '',
    appId: '1:975047231758:web:26f0bba399938b22dc6f5f',
    messagingSenderId: '975047231758',
    projectId: 'paydas-a4506',
    authDomain: 'paydas-a4506.firebaseapp.com',
    storageBucket: 'paydas-a4506.firebasestorage.app',
  );
}
